services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_DBNAME
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "5432:5432"
  web:
    image: student_api:$IMAGE_TAG
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_DBNAME=$DB_DBNAME
    depends_on:
      - db