---
# ConfigMap for PostgreSQL configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: student-api-ns
data:
  DB_DBNAME: "dummy"
---
# ServiceAccount for accessing db-secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: student-api-ns
---
# Role to allow access to db-secrets in external namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-secrets-access
  namespace: student-api-ns
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["db-secrets"]
    verbs: ["get"]
---
# RoleBinding to bind the ServiceAccount to the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-sa-db-secrets-access
  namespace: student-api-ns
subjects:
  - kind: ServiceAccount
    name: postgres-sa
    namespace: student-api-ns
roleRef:
  kind: Role
  name: db-secrets-access
  apiGroup: rbac.authorization.k8s.io
---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: student-api-ns
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres-sa
      initContainers:
        # Init container for database migration
        # - name: db-migration
        #   image: migrate/migrate:latest # Specify version if needed, e.g., v4.17.1
        #   env:
        #     - name: DB_DBNAME
        #       valueFrom:
        #         configMapKeyRef:
        #           name: postgres-config
        #           key: DB_DBNAME
        #     - name: DB_USERNAME
        #       valueFrom:
        #         secretKeyRef:
        #           name: db-secrets
        #           key: DB_USERNAME
        #     - name: DB_PASSWORD
        #       valueFrom:
        #         secretKeyRef:
        #           name: db-secrets
        #           key: DB_PASSWORD
        #   command:
        #     - migrate
        #     - -path
        #     - /migrations
        #     - -database
        #     - postgres://$(DB_USERNAME):$(DB_PASSWORD)@postgres:5432/$(DB_DBNAME)?sslmode=disable
        #     - up
        #   volumeMounts:
        #     - name: migration-scripts
        #       mountPath: /migrations
      containers:
        # PostgreSQL container
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_DBNAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      # volumes:
      #   - name: migration-scripts
      #     configMap:
      #       name: migration-scripts
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
# ClusterIP Service for PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: student-api-ns
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres