apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-db-secrets
  namespace: student-api-ns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
      - secretKey: DB_USERNAME # Key in the Kubernetes Secret
        remoteRef:
          key: db/config       # Relative path to the Vault secret
          property: DB_USERNAME # Property within the Vault secret
      - secretKey: DB_PASSWORD # Key in the Kubernetes Secret
        remoteRef:
          key: db/config       # Relative path to the Vault secret
          property: DB_PASSWORD # Property within the Vault secret